import { Bed, Compass, Utensils, Mountain, Music, Landmark } from "lucide-react"

export const regions = [
  {
    slug: "hhohho",
    name: "Hhohho",
    tagline: "Cultural Heartland",
    description:
      "Home to the capital Mbabane and the Ezulwini Valley, known for its cultural attractions and royal residences.",
  },
  {
    slug: "manzini",
    name: "Manzini",
    tagline: "Commercial Hub",
    description: "The industrial and commercial center of Eswatini, featuring the country's largest urban area.",
  },
  {
    slug: "lubombo",
    name: "Lubombo",
    tagline: "Savannah Adventures",
    description: "Known for its diverse wildlife, game reserves, and the beautiful Lubombo Mountains.",
  },
  {
    slug: "shiselweni",
    name: "Shiselweni",
    tagline: "Untamed Wilderness",
    description: "A region of rolling hills, forests, and traditional rural Swazi life.",
  },
]

export const categories = [
  {
    slug: "accommodation",
    name: "Accommodation",
    icon: Bed,
    count: 124,
    description: "Find the perfect place to stay, from luxury lodges to traditional beehive huts.",
  },
  {
    slug: "tours",
    name: "Tours",
    icon: Compass,
    count: 87,
    description: "Guided experiences that showcase the best of Eswatini's landscapes and culture.",
  },
  {
    slug: "dining",
    name: "Dining",
    icon: Utensils,
    count: 56,
    description: "Taste traditional Swazi cuisine and international dishes at restaurants across the kingdom.",
  },
  {
    slug: "cultural",
    name: "Cultural Sites",
    icon: Landmark,
    count: 42,
    description: "Explore Eswatini's rich cultural heritage through museums, villages, and historical sites.",
  },
  {
    slug: "adventure",
    name: "Adventure",
    icon: Mountain,
    count: 38,
    description: "Get your adrenaline pumping with hiking, rafting, and other outdoor activities.",
  },
  {
    slug: "entertainment",
    name: "Entertainment",
    icon: Music,
    count: 35,
    description: "Experience Eswatini's vibrant nightlife, music venues, and entertainment spots.",
  },
]

// Featured provider for the homepage
export const featuredProvider = {
  id: "featured-provider",
  name: "Hilton Mbabane",
  category: "accommodation",
  region: "hhohho",
  location: "Mbabane",
  address: "Main Street, Mbabane, Eswatini",
  description:
    "Experience luxury in the heart of Mbabane with stunning views of the surrounding mountains and valleys. Our 5-star hotel offers world-class amenities and exceptional service.",
  rating: 4.9,
  reviewCount: 245,
  price: 2500,
  tags: ["Luxury", "City Center", "Mountain View"],
  amenities: [
    "Swimming Pool",
    "Spa",
    "Fitness Center",
    "Restaurant",
    "Bar",
    "Conference Rooms",
    "Free Wi-Fi",
    "Room Service",
  ],
  services: [
    "24-hour Room Service",
    "Airport Transfers",
    "Concierge Service",
    "Laundry Service",
    "Business Center",
    "Tour Arrangements",
  ],
  phone: "+268 2404 1234",
  email: "reservations@hiltonmbabane.sz",
  website: "https://www.hiltonmbabane.sz",
}

export const providers = [
  {
    id: "mantenga-cultural-village",
    name: "Mantenga Cultural Village",
    category: "cultural",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Mantenga Nature Reserve, Ezulwini Valley, Eswatini",
    description:
      "Experience traditional Swazi culture through dance performances, crafts demonstrations, and a guided tour of a reconstructed Swazi homestead.",
    rating: 4.8,
    reviewCount: 156,
    price: 250,
    tags: ["Cultural Experience", "Traditional Dance", "Guided Tours"],
    amenities: ["Craft Shop", "Restaurant", "Parking", "Restrooms", "Wheelchair Accessible"],
    services: [
      "Traditional Sibhaca Dance Performances",
      "Guided Tours of Traditional Homestead",
      "Cultural Workshops",
      "Craft Demonstrations",
      "Traditional Swazi Meals",
    ],
    phone: "+268 2416 1179",
    email: "info@mantengaculturalvillage.co.sz",
    website: "https://www.mantengaculturalvillage.co.sz",
  },
  {
    id: "mlilwane-wildlife-sanctuary",
    name: "Mlilwane Wildlife Sanctuary",
    category: "adventure",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Ezulwini Valley, Eswatini",
    description:
      "Eswatini's oldest protected area offering wildlife viewing, hiking, mountain biking, and horseback riding in a beautiful savanna setting.",
    rating: 4.7,
    reviewCount: 203,
    price: 150,
    tags: ["Wildlife", "Outdoor Activities", "Nature"],
    amenities: ["Accommodation", "Restaurant", "Camping", "Swimming Pool", "Gift Shop"],
    services: [
      "Guided Game Drives",
      "Horseback Safaris",
      "Mountain Biking Trails",
      "Hiking Trails",
      "Bird Watching Tours",
    ],
    phone: "+268 2528 3943",
    email: "reservations@biggameparks.org",
    website: "https://www.biggameparks.org/mlilwane",
  },
  {
    id: "royal-swazi-spa",
    name: "Royal Swazi Spa",
    category: "accommodation",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Old Mbabane-Manzini Main Road, Ezulwini Valley",
    description:
      "Luxury resort featuring a hotel, spa, casino, and championship golf course in the heart of the Ezulwini Valley.",
    rating: 4.5,
    reviewCount: 178,
    price: 1500,
    tags: ["Luxury", "Golf", "Spa"],
    amenities: ["Swimming Pool", "Spa", "Casino", "Golf Course", "Restaurants", "Bars", "Gym", "Conference Facilities"],
    services: ["Spa Treatments", "Golf Lessons", "Casino Gaming", "Fine Dining", "Conference Hosting"],
    phone: "+268 2416 5000",
    email: "reservations@royalswazi.sz",
    website: "https://www.royalswazi.sz",
  },
  {
    id: "swazi-candles",
    name: "Swazi Candles Craft Market",
    category: "cultural",
    region: "manzini",
    location: "Malkerns Valley",
    address: "Malkerns Valley, Eswatini",
    description:
      "Artisan marketplace featuring handcrafted candles, textiles, and other local crafts, with live demonstrations of candle making.",
    rating: 4.6,
    reviewCount: 124,
    price: 0,
    tags: ["Shopping", "Crafts", "Souvenirs"],
    amenities: ["Cafe", "Parking", "Restrooms"],
    services: ["Candle Making Demonstrations", "Craft Shopping", "Cafe Services"],
    phone: "+268 2528 3266",
    email: "info@swazicandles.com",
    website: "https://www.swazicandles.com",
  },
  {
    id: "hlane-royal-national-park",
    name: "Hlane Royal National Park",
    category: "adventure",
    region: "lubombo",
    location: "Lubombo Region",
    address: "Lubombo Region, Eswatini",
    description:
      "Eswatini's largest protected area, home to lions, elephants, rhinos, and diverse birdlife, offering game drives and guided walks.",
    rating: 4.9,
    reviewCount: 187,
    price: 200,
    tags: ["Big Five", "Safari", "Wildlife"],
    amenities: ["Accommodation", "Restaurant", "Camping", "Game Viewing Hides"],
    services: ["Game Drives", "Guided Bush Walks", "Bird Watching Tours", "Rhino Tracking", "Bush Dinners"],
    phone: "+268 2383 8100",
    email: "reservations@biggameparks.org",
    website: "https://www.biggameparks.org/hlane",
  },
  {
    id: "shewula-mountain-camp",
    name: "Shewula Mountain Camp",
    category: "accommodation",
    region: "lubombo",
    location: "Shewula Community",
    address: "Shewula Community, Lubombo Mountains",
    description:
      "Community-owned eco-lodge offering authentic cultural experiences and stunning views of the Lubombo Mountains and plains.",
    rating: 4.7,
    reviewCount: 92,
    price: 450,
    tags: ["Eco-Tourism", "Community Project", "Cultural Experience"],
    amenities: ["Traditional Accommodation", "Restaurant", "Guided Tours", "Cultural Activities"],
    services: [
      "Cultural Village Tours",
      "Traditional Meals",
      "Hiking Trails",
      "Bird Watching",
      "Community Project Visits",
    ],
    phone: "+268 7602 0202",
    email: "bookings@shewulacamp.org",
    website: "https://www.shewulacamp.org",
  },
  {
    id: "malolotja-nature-reserve",
    name: "Malolotja Nature Reserve",
    category: "adventure",
    region: "hhohho",
    location: "Northwestern Eswatini",
    address: "Piggs Peak Road, Northwestern Eswatini",
    description:
      "Spectacular mountain wilderness with the highest waterfall in Eswatini, offering hiking trails, trout fishing, and pristine nature.",
    rating: 4.8,
    reviewCount: 134,
    price: 120,
    tags: ["Hiking", "Waterfall", "Nature Reserve"],
    amenities: ["Camping", "Hiking Trails", "Visitor Center", "Parking"],
    services: ["Guided Hikes", "Trout Fishing", "Bird Watching", "Photography Tours"],
    phone: "+268 2437 1178",
    email: "info@malolotja.org.sz",
    website: "https://www.malolotja.org.sz",
  },
  {
    id: "mkhaya-game-reserve",
    name: "Mkhaya Game Reserve",
    category: "adventure",
    region: "shiselweni",
    location: "Southern Eswatini",
    address: "Southern Eswatini",
    description:
      "Exclusive game reserve dedicated to endangered species conservation, offering intimate wildlife encounters with black rhinos and sable antelope.",
    rating: 4.9,
    reviewCount: 89,
    price: 800,
    tags: ["Conservation", "Endangered Species", "Exclusive"],
    amenities: ["Luxury Accommodation", "Restaurant", "Game Drives"],
    services: ["Conservation Tours", "Rhino Tracking", "Night Drives", "Bush Walks"],
    phone: "+268 2528 3943",
    email: "reservations@biggameparks.org",
    website: "https://www.biggameparks.org/mkhaya",
  },
  {
    id: "ngwenya-glass-village",
    name: "Ngwenya Glass Village",
    category: "cultural",
    region: "hhohho",
    location: "Ngwenya",
    address: "Ngwenya Border, Eswatini",
    description:
      "Famous glass factory where skilled artisans create beautiful glassware from recycled materials, with live demonstrations and shopping.",
    rating: 4.5,
    reviewCount: 167,
    price: 0,
    tags: ["Glass Making", "Recycling", "Crafts"],
    amenities: ["Factory Tours", "Gift Shop", "Parking", "Cafe"],
    services: ["Glass Blowing Demonstrations", "Shopping", "Educational Tours"],
    phone: "+268 2442 4053",
    email: "info@ngwenyaglass.co.sz",
    website: "https://www.ngwenyaglass.co.sz",
  },
  {
    id: "lobamba-royal-village",
    name: "Lobamba Royal Village",
    category: "cultural",
    region: "hhohho",
    location: "Lobamba",
    address: "Lobamba, Eswatini",
    description:
      "Traditional and legislative capital of Eswatini, home to the Parliament, National Museum, and important cultural sites.",
    rating: 4.6,
    reviewCount: 145,
    price: 100,
    tags: ["Royal Capital", "Museum", "Parliament"],
    amenities: ["Museum", "Parliament Building", "Cultural Center", "Parking"],
    services: ["Guided Tours", "Cultural Education", "Historical Tours"],
    phone: "+268 2416 1179",
    email: "info@lobamba.gov.sz",
    website: "https://www.lobamba.gov.sz",
  },
  {
    id: "sibebe-rock",
    name: "Sibebe Rock",
    category: "adventure",
    region: "hhohho",
    location: "Near Mbabane",
    address: "Mbabane, Eswatini",
    description:
      "The world's second-largest granite dome, offering challenging hiking and rock climbing with spectacular panoramic views.",
    rating: 4.7,
    reviewCount: 98,
    price: 80,
    tags: ["Rock Climbing", "Hiking", "Granite Dome"],
    amenities: ["Hiking Trails", "Climbing Routes", "Viewpoints"],
    services: ["Guided Climbs", "Hiking Tours", "Photography Sessions"],
    phone: "+268 2404 2531",
    email: "info@sibebe.sz",
    website: "https://www.sibebe.sz",
  },
  {
    id: "maguga-dam",
    name: "Maguga Dam",
    category: "adventure",
    region: "hhohho",
    location: "Komati River",
    address: "Komati River, Northern Eswatini",
    description:
      "Scenic dam offering water sports, fishing, and beautiful mountain views, popular for weekend getaways and outdoor activities.",
    rating: 4.4,
    reviewCount: 112,
    price: 60,
    tags: ["Water Sports", "Fishing", "Scenic Views"],
    amenities: ["Boat Launch", "Fishing Spots", "Picnic Areas", "Parking"],
    services: ["Boat Rentals", "Fishing Guides", "Water Sports"],
    phone: "+268 2437 1234",
    email: "info@magugadam.sz",
    website: "https://www.magugadam.sz",
  },
  {
    id: "phophonyane-falls",
    name: "Phophonyane Falls",
    category: "adventure",
    region: "hhohho",
    location: "Piggs Peak",
    address: "Piggs Peak, Eswatini",
    description:
      "Beautiful waterfall and nature reserve with hiking trails, swimming pools, and diverse birdlife in a pristine forest setting.",
    rating: 4.6,
    reviewCount: 87,
    price: 90,
    tags: ["Waterfall", "Swimming", "Forest"],
    amenities: ["Hiking Trails", "Swimming Pools", "Picnic Areas", "Accommodation"],
    services: ["Guided Walks", "Bird Watching", "Nature Photography"],
    phone: "+268 2437 1319",
    email: "info@phophonyane.co.sz",
    website: "https://www.phophonyane.co.sz",
  },
  {
    id: "hawane-resort",
    name: "Hawane Resort",
    category: "accommodation",
    region: "hhohho",
    location: "Piggs Peak",
    address: "Piggs Peak, Eswatini",
    description:
      "Mountain resort offering comfortable accommodation with stunning views, outdoor activities, and traditional Swazi hospitality.",
    rating: 4.3,
    reviewCount: 156,
    price: 650,
    tags: ["Mountain Resort", "Outdoor Activities", "Family Friendly"],
    amenities: ["Swimming Pool", "Restaurant", "Conference Facilities", "Hiking Trails"],
    services: ["Outdoor Activities", "Conference Hosting", "Family Programs"],
    phone: "+268 2437 1319",
    email: "reservations@hawane.co.sz",
    website: "https://www.hawane.co.sz",
  },
  {
    id: "foresters-arms-hotel",
    name: "Foresters Arms Hotel",
    category: "accommodation",
    region: "hhohho",
    location: "Mbabane",
    address: "Mbabane, Eswatini",
    description:
      "Historic hotel in the heart of Mbabane offering comfortable accommodation with easy access to the city's attractions and business district.",
    rating: 4.2,
    reviewCount: 189,
    price: 850,
    tags: ["Historic", "City Center", "Business"],
    amenities: ["Restaurant", "Bar", "Conference Rooms", "Wi-Fi"],
    services: ["Business Services", "City Tours", "Airport Transfers"],
    phone: "+268 2404 2115",
    email: "reservations@forestersarms.sz",
    website: "https://www.forestersarms.sz",
  },
  {
    id: "mountain-inn",
    name: "Mountain Inn",
    category: "accommodation",
    region: "hhohho",
    location: "Mbabane",
    address: "Mbabane, Eswatini",
    description:
      "Boutique hotel offering personalized service and comfortable accommodation with beautiful mountain views and modern amenities.",
    rating: 4.4,
    reviewCount: 134,
    price: 750,
    tags: ["Boutique", "Mountain Views", "Personalized Service"],
    amenities: ["Restaurant", "Bar", "Wi-Fi", "Parking"],
    services: ["Concierge", "Tour Arrangements", "Business Services"],
    phone: "+268 2404 2781",
    email: "info@mountaininn.sz",
    website: "https://www.mountaininn.sz",
  },
  {
    id: "lugogo-sun",
    name: "Lugogo Sun",
    category: "accommodation",
    region: "manzini",
    location: "Manzini",
    address: "Manzini, Eswatini",
    description:
      "Modern hotel in Manzini offering comfortable accommodation for business and leisure travelers with excellent facilities.",
    rating: 4.1,
    reviewCount: 167,
    price: 720,
    tags: ["Modern", "Business", "Convenient Location"],
    amenities: ["Swimming Pool", "Restaurant", "Conference Facilities", "Gym"],
    services: ["Business Center", "Airport Transfers", "Laundry"],
    phone: "+268 2505 6061",
    email: "reservations@lugogosun.sz",
    website: "https://www.lugogosun.sz",
  },
  {
    id: "nhlangano-sun",
    name: "Nhlangano Sun",
    category: "accommodation",
    region: "shiselweni",
    location: "Nhlangano",
    address: "Nhlangano, Eswatini",
    description:
      "Comfortable hotel in southern Eswatini offering a peaceful retreat with casino, restaurant, and recreational facilities.",
    rating: 4.0,
    reviewCount: 143,
    price: 680,
    tags: ["Casino", "Peaceful", "Recreational"],
    amenities: ["Casino", "Restaurant", "Swimming Pool", "Conference Rooms"],
    services: ["Gaming", "Entertainment", "Conference Hosting"],
    phone: "+268 2207 8061",
    email: "reservations@nhlanganosun.sz",
    website: "https://www.nhlanganosun.sz",
  },
  {
    id: "piggs-peak-hotel",
    name: "Piggs Peak Hotel",
    category: "accommodation",
    region: "hhohho",
    location: "Piggs Peak",
    address: "Piggs Peak, Eswatini",
    description:
      "Historic hotel in the mountains offering comfortable accommodation with easy access to hiking trails and natural attractions.",
    rating: 4.2,
    reviewCount: 98,
    price: 580,
    tags: ["Historic", "Mountain Location", "Nature Access"],
    amenities: ["Restaurant", "Bar", "Conference Room", "Parking"],
    services: ["Nature Tours", "Hiking Guides", "Local Excursions"],
    phone: "+268 2437 1104",
    email: "info@piggspeakhotel.sz",
    website: "https://www.piggspeakhotel.sz",
  },
  {
    id: "summerfield-botanical-garden",
    name: "Summerfield Botanical Garden",
    category: "cultural",
    region: "manzini",
    location: "Manzini",
    address: "Manzini, Eswatini",
    description:
      "Beautiful botanical garden showcasing indigenous plants and flowers, perfect for nature lovers and educational visits.",
    rating: 4.3,
    reviewCount: 76,
    price: 50,
    tags: ["Botanical Garden", "Indigenous Plants", "Educational"],
    amenities: ["Walking Trails", "Visitor Center", "Parking", "Picnic Areas"],
    services: ["Guided Tours", "Educational Programs", "Plant Sales"],
    phone: "+268 2505 2344",
    email: "info@summerfield.sz",
    website: "https://www.summerfield.sz",
  },
  {
    id: "king-sobhuza-memorial-park",
    name: "King Sobhuza II Memorial Park",
    category: "cultural",
    region: "hhohho",
    location: "Lobamba",
    address: "Lobamba, Eswatini",
    description:
      "Memorial park dedicated to King Sobhuza II, featuring cultural exhibits, traditional architecture, and peaceful gardens.",
    rating: 4.5,
    reviewCount: 123,
    price: 75,
    tags: ["Memorial", "Cultural Heritage", "Royal History"],
    amenities: ["Museum", "Gardens", "Cultural Exhibits", "Parking"],
    services: ["Historical Tours", "Cultural Education", "Photography"],
    phone: "+268 2416 1179",
    email: "info@sobhuzamemorial.sz",
    website: "https://www.sobhuzamemorial.sz",
  },
  {
    id: "matsamo-cultural-village",
    name: "Matsamo Cultural Village",
    category: "cultural",
    region: "lubombo",
    location: "Matsamo",
    address: "Matsamo, Lubombo Region, Eswatini",
    description:
      "Authentic cultural village experience showcasing traditional Swazi life, customs, and crafts in a rural setting.",
    rating: 4.4,
    reviewCount: 89,
    price: 180,
    tags: ["Cultural Village", "Traditional Life", "Rural Experience"],
    amenities: ["Traditional Huts", "Craft Center", "Cultural Performances"],
    services: ["Cultural Tours", "Traditional Meals", "Craft Workshops"],
    phone: "+268 2383 8234",
    email: "info@matsamovillage.sz",
    website: "https://www.matsamovillage.sz",
  },
  {
    id: "lidwala-backpacker-lodge",
    name: "Lidwala Backpacker Lodge",
    category: "accommodation",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Ezulwini Valley, Eswatini",
    description:
      "Budget-friendly backpacker lodge offering dormitory and private rooms with a social atmosphere and outdoor activities.",
    rating: 4.1,
    reviewCount: 234,
    price: 180,
    tags: ["Budget", "Backpacker", "Social"],
    amenities: ["Dormitories", "Private Rooms", "Kitchen", "Common Area"],
    services: ["Tour Bookings", "Activity Arrangements", "Transport"],
    phone: "+268 2416 2636",
    email: "info@lidwala.com",
    website: "https://www.lidwala.com",
  },
  {
    id: "maguga-lodge",
    name: "Maguga Lodge",
    category: "accommodation",
    region: "hhohho",
    location: "Maguga Dam",
    address: "Maguga Dam, Eswatini",
    description:
      "Lakeside lodge offering comfortable accommodation with water activities, fishing, and beautiful dam views.",
    rating: 4.3,
    reviewCount: 87,
    price: 620,
    tags: ["Lakeside", "Water Activities", "Scenic"],
    amenities: ["Restaurant", "Boat Launch", "Fishing Equipment", "Conference Room"],
    services: ["Boat Rentals", "Fishing Guides", "Water Sports"],
    phone: "+268 2437 1567",
    email: "reservations@magugalodge.sz",
    website: "https://www.magugalodge.sz",
  },
  // Entertainment providers
  {
    id: "solanis-entertainment",
    name: "Solanis Entertainment",
    category: "entertainment",
    region: "manzini",
    location: "Manzini",
    address: "Main Street, Manzini, Eswatini",
    description:
      "Premier entertainment venue featuring live music, DJ nights, and cultural performances in a vibrant atmosphere.",
    rating: 4.8,
    reviewCount: 156,
    price: 100,
    tags: ["Live Music", "Nightlife", "Cultural Performances"],
    amenities: ["Bar", "Dance Floor", "VIP Lounge", "Outdoor Terrace", "Restaurant"],
    services: [
      "Live Music Events",
      "DJ Nights",
      "Private Event Hosting",
      "Cultural Performances",
      "Food & Beverage Service",
    ],
    phone: "+268 2505 1234",
    email: "info@solanis.sz",
    website: "https://www.solanis.sz",
  },
  {
    id: "albert-millin",
    name: "Albert Millin",
    category: "entertainment",
    region: "hhohho",
    location: "Mbabane",
    address: "Industrial Area, Mbabane, Eswatini",
    description:
      "Premier entertainment venue offering live music performances, cultural shows, and a vibrant atmosphere for locals and visitors alike.",
    rating: 4.7,
    reviewCount: 132,
    price: 80,
    tags: ["Live Music", "Cultural Shows", "Local Venue"],
    amenities: ["Bar", "Performance Stage", "Sound System", "Outdoor Seating", "Food Service"],
    services: [
      "Live Music Events",
      "Cultural Performances",
      "Private Event Hosting",
      "Food & Beverage Service",
      "Local Artist Showcases",
    ],
    phone: "+268 2404 5678",
    email: "events@albertmillin.sz",
    website: "https://www.albertmillin.sz",
  },
  {
    id: "the-exchange",
    name: "The Exchange",
    category: "entertainment",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Valley Road, Ezulwini, Eswatini",
    description:
      "Modern entertainment complex featuring a cinema, bowling alley, arcade games, and a variety of dining options.",
    rating: 4.6,
    reviewCount: 178,
    price: 150,
    tags: ["Cinema", "Bowling", "Arcade", "Family Entertainment"],
    amenities: ["Cinema", "Bowling Alley", "Arcade Games", "Restaurants", "Bar", "Parking"],
    services: [
      "Movie Screenings",
      "Bowling Lanes",
      "Arcade Gaming",
      "Birthday Parties",
      "Corporate Events",
      "Food & Beverage Service",
    ],
    phone: "+268 2416 7890",
    email: "info@theexchange.sz",
    website: "https://www.theexchange.sz",
  },
  // Add featured provider to the providers array
  featuredProvider,
]

// Real tour providers in Eswatini
export const tourProviders = [
  {
    id: "all-out-africa",
    name: "All Out Africa",
    category: "tours",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Ezulwini Valley, Eswatini",
    description:
      "Comprehensive tour operator offering cultural tours, wildlife safaris, and adventure activities across Eswatini.",
    rating: 4.7,
    reviewCount: 189,
    price: 450,
    tags: ["Cultural Tours", "Wildlife Safaris", "Adventure"],
    amenities: ["Transportation", "Professional Guides", "Refreshments", "Photography"],
    services: ["Day Tours", "Multi-day Safaris", "Cultural Experiences", "Adventure Activities"],
    phone: "+268 2416 2180",
    email: "info@alloutafrica.com",
    website: "https://www.alloutafrica.com",
  },
  {
    id: "swazi-trails",
    name: "Swazi Trails",
    category: "tours",
    region: "manzini",
    location: "Malkerns Valley",
    address: "Malkerns Valley, Eswatini",
    description:
      "Specialist hiking and adventure tour company offering guided trails through Eswatini's most scenic landscapes.",
    rating: 4.8,
    reviewCount: 145,
    price: 380,
    tags: ["Hiking", "Adventure", "Nature Trails"],
    amenities: ["Hiking Equipment", "Expert Guides", "Safety Gear", "Packed Lunches"],
    services: ["Guided Hikes", "Multi-day Trails", "Rock Climbing", "Nature Photography"],
    phone: "+268 2528 3198",
    email: "trails@swazitrails.sz",
    website: "https://www.swazitrails.sz",
  },
  {
    id: "big-game-parks",
    name: "Big Game Parks Foundation",
    category: "tours",
    region: "lubombo",
    location: "Hlane Royal National Park",
    address: "Hlane Royal National Park, Eswatini",
    description:
      "Conservation-focused tours in Eswatini's premier game reserves, offering authentic wildlife experiences.",
    rating: 4.9,
    reviewCount: 234,
    price: 520,
    tags: ["Wildlife", "Conservation", "Game Drives"],
    amenities: ["Game Vehicles", "Expert Rangers", "Binoculars", "Field Guides"],
    services: ["Game Drives", "Walking Safaris", "Rhino Tracking", "Conservation Education"],
    phone: "+268 2528 3943",
    email: "tours@biggameparks.org",
    website: "https://www.biggameparks.org",
  },
  {
    id: "eswatini-cultural-tours",
    name: "Eswatini Cultural Tours",
    category: "tours",
    region: "hhohho",
    location: "Lobamba",
    address: "Lobamba, Eswatini",
    description: "Authentic cultural experiences showcasing Swazi traditions, royal heritage, and local communities.",
    rating: 4.6,
    reviewCount: 167,
    price: 320,
    tags: ["Cultural Heritage", "Royal Sites", "Traditional Villages"],
    amenities: ["Cultural Guides", "Traditional Meals", "Craft Demonstrations"],
    services: ["Royal Village Tours", "Cultural Performances", "Traditional Craft Workshops"],
    phone: "+268 2416 1298",
    email: "culture@eswatinitours.sz",
    website: "https://www.eswatinitours.sz",
  },
  {
    id: "adventure-eswatini",
    name: "Adventure Eswatini",
    category: "tours",
    region: "hhohho",
    location: "Mbabane",
    address: "Mbabane, Eswatini",
    description: "Adrenaline-pumping adventure tours including white water rafting, abseiling, and extreme sports.",
    rating: 4.5,
    reviewCount: 198,
    price: 480,
    tags: ["Extreme Sports", "White Water Rafting", "Abseiling"],
    amenities: ["Safety Equipment", "Professional Instructors", "Insurance", "Photography"],
    services: ["White Water Rafting", "Abseiling", "Canopy Tours", "Rock Climbing"],
    phone: "+268 2404 3567",
    email: "adventure@eswatiniadventure.sz",
    website: "https://www.eswatiniadventure.sz",
  },
]

// Real dining providers in Eswatini
export const diningProviders = [
  {
    id: "ramblas-restaurant",
    name: "Ramblas Restaurant",
    category: "dining",
    region: "hhohho",
    location: "Mbabane",
    address: "Mbabane, Eswatini",
    description:
      "Upscale restaurant offering international cuisine with a focus on fresh, local ingredients and excellent service.",
    rating: 4.6,
    reviewCount: 234,
    price: 280,
    tags: ["International Cuisine", "Fine Dining", "Local Ingredients"],
    amenities: ["Indoor Seating", "Bar", "Private Dining", "Wine Cellar"],
    services: ["Fine Dining", "Wine Pairing", "Private Events", "Catering"],
    phone: "+268 2404 6789",
    email: "reservations@ramblas.sz",
    website: "https://www.ramblas.sz",
  },
  {
    id: "malandelas-restaurant",
    name: "Malandela's Restaurant",
    category: "dining",
    region: "manzini",
    location: "Malkerns Valley",
    address: "House on Fire, Malkerns Valley, Eswatini",
    description:
      "Unique restaurant at the famous House on Fire venue, serving contemporary cuisine in an artistic atmosphere.",
    rating: 4.5,
    reviewCount: 189,
    price: 250,
    tags: ["Contemporary", "Artistic Venue", "Live Music"],
    amenities: ["Outdoor Terrace", "Art Gallery", "Live Music Venue", "Bar"],
    services: ["Contemporary Dining", "Live Entertainment", "Art Exhibitions", "Event Hosting"],
    phone: "+268 2528 3115",
    email: "dining@houseonfire.sz",
    website: "https://www.houseonfire.sz",
  },
  {
    id: "calabash-restaurant",
    name: "Calabash Restaurant",
    category: "dining",
    region: "hhohho",
    location: "Ezulwini Valley",
    address: "Ezulwini Valley, Eswatini",
    description:
      "Traditional Swazi restaurant offering authentic local cuisine in a cultural setting with traditional performances.",
    rating: 4.4,
    reviewCount: 156,
    price: 180,
    tags: ["Traditional Swazi", "Cultural Dining", "Authentic"],
    amenities: ["Traditional Decor", "Cultural Performances", "Outdoor Seating"],
    services: ["Traditional Meals", "Cultural Shows", "Cooking Classes"],
    phone: "+268 2416 4321",
    email: "info@calabash.sz",
    website: "https://www.calabash.sz",
  },
]

// Real cultural providers in Eswatini
export const culturalProviders = [
  {
    id: "national-museum",
    name: "Eswatini National Museum",
    category: "cultural",
    region: "hhohho",
    location: "Lobamba",
    address: "Lobamba, Eswatini",
    description:
      "Premier museum showcasing Swazi culture, history, and natural heritage with extensive collections and exhibits.",
    rating: 4.5,
    reviewCount: 198,
    price: 80,
    tags: ["Museum", "History", "Cultural Heritage"],
    amenities: ["Exhibition Halls", "Gift Shop", "Parking", "Guided Tours"],
    services: ["Museum Tours", "Educational Programs", "Cultural Workshops"],
    phone: "+268 2416 1179",
    email: "info@museum.gov.sz",
    website: "https://www.museum.gov.sz",
  },
  {
    id: "parliament-building",
    name: "Parliament Building",
    category: "cultural",
    region: "hhohho",
    location: "Lobamba",
    address: "Lobamba, Eswatini",
    description:
      "Seat of Eswatini's parliament, offering guided tours of this important government building and its history.",
    rating: 4.2,
    reviewCount: 87,
    price: 60,
    tags: ["Government", "Architecture", "History"],
    amenities: ["Guided Tours", "Visitor Center", "Security"],
    services: ["Parliamentary Tours", "Civic Education", "Historical Information"],
    phone: "+268 2416 1234",
    email: "tours@parliament.gov.sz",
    website: "https://www.parliament.gov.sz",
  },
]

// Real adventure providers in Eswatini
export const adventureProviders = [
  {
    id: "usutu-forest",
    name: "Usutu Forest",
    category: "adventure",
    region: "shiselweni",
    location: "Southern Eswatini",
    address: "Southern Eswatini",
    description:
      "Largest man-made forest in the southern hemisphere, offering hiking, mountain biking, and nature experiences.",
    rating: 4.3,
    reviewCount: 134,
    price: 100,
    tags: ["Forest", "Mountain Biking", "Hiking"],
    amenities: ["Hiking Trails", "Mountain Bike Routes", "Picnic Areas"],
    services: ["Guided Hikes", "Bike Rentals", "Nature Tours"],
    phone: "+268 2207 4567",
    email: "info@usutuforest.sz",
    website: "https://www.usutuforest.sz",
  },
  {
    id: "great-usutu-river",
    name: "Great Usutu River",
    category: "adventure",
    region: "shiselweni",
    location: "Southern Eswatini",
    address: "Southern Eswatini",
    description: "Premier white water rafting destination offering thrilling rapids and scenic river journeys.",
    rating: 4.7,
    reviewCount: 167,
    price: 350,
    tags: ["White Water Rafting", "River Adventure", "Scenic"],
    amenities: ["Safety Equipment", "Professional Guides", "Transport"],
    services: ["White Water Rafting", "River Tubing", "Scenic Floats"],
    phone: "+268 2207 8901",
    email: "rafting@usuturiver.sz",
    website: "https://www.usuturiver.sz",
  },
]

// Add all providers to the main providers array
export const allProviders = [
  ...providers,
  ...tourProviders,
  ...diningProviders,
  ...culturalProviders,
  ...adventureProviders,
]

export const events = [
  {
    id: "umhlanga-reed-dance",
    name: "Umhlanga Reed Dance",
    category: "cultural",
    region: "hhohho",
    location: "Ludzidzini Royal Village",
    date: "2025-08-30",
    time: "All Day",
    description:
      "Annual traditional ceremony where thousands of unmarried girls and young women gather to pay homage to the Queen Mother (Indlovukazi). One of Eswatini's most important cultural events.",
    image: "/placeholder.svg?height=300&width=500&text=Umhlanga+Reed+Dance",
    price: 150,
    featured: true,
  },
  {
    id: "incwala-ceremony",
    name: "Incwala Ceremony",
    category: "cultural",
    region: "hhohho",
    location: "Lobamba Royal Village",
    date: "2025-12-21",
    time: "All Day",
    description:
      "The most sacred national event in Eswatini, celebrating kingship and the first fruits of the harvest. A deeply spiritual ceremony marking the summer solstice.",
    image: "/placeholder.svg?height=300&width=500&text=Incwala+Ceremony",
    price: 200,
    featured: true,
  },
  {
    id: "mtn-bushfire-festival",
    name: "MTN Bushfire Festival",
    category: "music",
    region: "manzini",
    location: "House on Fire, Malkerns Valley",
    date: "2025-05-24",
    time: "3 Days",
    description:
      "Southern Africa's premier music and arts festival celebrating the human spirit. Features international and local artists, art exhibitions, and cultural performances.",
    image: "/placeholder.svg?height=300&width=500&text=MTN+Bushfire+Festival",
    price: 450,
    featured: true,
  },
  {
    id: "kings-birthday",
    name: "King's Birthday",
    category: "national",
    region: "hhohho",
    location: "Lobamba & Nationwide",
    date: "2025-04-19",
    time: "All Day",
    description:
      "National holiday celebrating the birthday of King Mswati III. Features royal ceremonies, cultural performances, and national celebrations.",
    image: "/placeholder.svg?height=300&width=500&text=King's+Birthday",
    price: 0,
    featured: false,
  },
  {
    id: "national-flag-day",
    name: "National Flag Day",
    category: "national",
    region: "hhohho",
    location: "Nationwide",
    date: "2025-04-25",
    time: "All Day",
    description:
      "Day dedicated to honoring the national flag of Eswatini. Features flag ceremonies, patriotic displays, and educational activities about national symbols.",
    image: "/placeholder.svg?height=300&width=500&text=National+Flag+Day",
    price: 0,
    featured: false,
  },
  {
    id: "marula-festival",
    name: "Marula Festival",
    category: "cultural",
    region: "lubombo",
    location: "Ebuhleni Royal Residence",
    date: "2025-02-15",
    time: "9:00 AM - 5:00 PM",
    description:
      "Traditional festival celebrating the harvest of marula fruit and the brewing of buganu (marula beer). Features traditional dancing, music, and cultural activities.",
    image: "/placeholder.svg?height=300&width=500&text=Marula+Festival",
    price: 100,
    featured: false,
  },
  {
    id: "luju-festival",
    name: "Luju Festival",
    category: "cultural",
    region: "shiselweni",
    location: "Nhlangano",
    date: "2025-06-28",
    time: "2 Days",
    description:
      "Contemporary cultural festival celebrating modern Swazi culture, music, and arts. Features local musicians, artists, and cultural innovators.",
    image: "/placeholder.svg?height=300&width=500&text=Luju+Festival",
    price: 180,
    featured: false,
  },
  {
    id: "sibhaca-dance-festival",
    name: "Sibhaca Dance Festival",
    category: "cultural",
    region: "manzini",
    location: "Malkerns Valley",
    date: "2025-07-12",
    time: "10:00 AM - 6:00 PM",
    description:
      "Traditional dance festival showcasing the energetic Sibhaca dance, a warrior dance performed by Swazi men. Features competitions and cultural performances.",
    image: "/placeholder.svg?height=300&width=500&text=Sibhaca+Dance+Festival",
    price: 120,
    featured: false,
  },
  {
    id: "eswatini-marathon",
    name: "Eswatini Marathon",
    category: "sports",
    region: "manzini",
    location: "Mbabane to Manzini",
    date: "2025-05-17",
    time: "6:00 AM - 2:00 PM",
    description:
      "Annual marathon event attracting local and international runners through the beautiful landscapes of Eswatini. Features full marathon, half marathon, and fun runs.",
    image: "/placeholder.svg?height=300&width=500&text=Eswatini+Marathon",
    price: 250,
    featured: false,
  },
  {
    id: "heritage-day",
    name: "Heritage Day",
    category: "cultural",
    region: "hhohho",
    location: "Lobamba",
    date: "2025-09-24",
    time: "All Day",
    description:
      "Day dedicated to celebrating Eswatini's rich cultural heritage. Features traditional performances, craft exhibitions, and cultural education programs.",
    image: "/placeholder.svg?height=300&width=500&text=Heritage+Day",
    price: 50,
    featured: false,
  },
  {
    id: "youth-day",
    name: "Youth Day",
    category: "national",
    region: "manzini",
    location: "Manzini",
    date: "2025-06-16",
    time: "All Day",
    description:
      "National day celebrating the youth of Eswatini. Features youth competitions, educational programs, and cultural activities aimed at empowering young people.",
    image: "/placeholder.svg?height=300&width=500&text=Youth+Day",
    price: 0,
    featured: false,
  },
  {
    id: "womens-day",
    name: "Women's Day",
    category: "national",
    region: "hhohho",
    location: "Mbabane",
    date: "2025-03-08",
    time: "All Day",
    description:
      "International Women's Day celebration in Eswatini, honoring the contributions of women to society. Features women's empowerment programs and cultural activities.",
    image: "/placeholder.svg?height=300&width=500&text=Women's+Day",
    price: 0,
    featured: false,
  },
  {
    id: "eswatini-trade-fair",
    name: "Eswatini International Trade Fair",
    category: "business",
    region: "manzini",
    location: "Manzini",
    date: "2025-08-15",
    time: "5 Days",
    description:
      "Annual trade fair showcasing local and international businesses, products, and services. Features exhibitions, business networking, and cultural entertainment.",
    image: "/placeholder.svg?height=300&width=500&text=Trade+Fair",
    price: 80,
    featured: false,
  },
]

// Get featured events for homepage (only 3)
export const getFeaturedEvents = () => {
  return events.filter((event) => event.featured).slice(0, 3)
}

// Get all events for events page
export const getAllEvents = () => {
  return events
}
